#!/usr/bin/env python3
"""Regenerates the manual's parameter reference from resources/help/reference.md.

The in-plugin help and the manual are the same words. Whichever a user opens,
they should get the same answer, and nobody should have to remember to update
the other one.

So there is one source — `resources/help/reference.md`, which the plugin reads
through BinaryData — and this script writes its content into `docs/MANUAL.md`
between two markers. CI runs it with `--check` and fails if the file on disk
differs from what would be generated, which is what stops the two drifting.

    scripts/gen-docs.py            rewrite docs/MANUAL.md
    scripts/gen-docs.py --check    exit 1 if it would change anything
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "resources" / "help" / "reference.md"
MANUAL = ROOT / "docs" / "MANUAL.md"

BEGIN = "<!-- BEGIN GENERATED PARAMETER REFERENCE -->"
END = "<!-- END GENERATED PARAMETER REFERENCE -->"

# The order families appear in the manual. Anything not listed here is appended
# afterwards in source order, so a new family shows up rather than vanishing.
FAMILY_ORDER = [
    ("Global", ("inGain", "outGain", "mix", "autoGain", "numBands", "osFactor",
                "osOffline", "xoverMode", "stereoMode", "dither", "xoverN")),
    ("Per band", ("bandN",)),
    ("Modulation sources", ("lfoN", "egN", "efN", "xy", "midiN", "macroN")),
]


class Article:
    def __init__(self, kind: str) -> None:
        self.kind = kind
        self.name = ""
        self.range = ""
        self.body: list[str] = []
        self.when = ""

    @property
    def prose(self) -> str:
        return " ".join(self.body).strip()


def parse(text: str) -> list[Article]:
    """Mirrors src/gui/tutorial/Reference.cpp. If you change one, change both —
    the test that compares them is the only thing keeping them honest."""
    articles: list[Article] = []
    current: Article | None = None

    in_when = False

    for raw in text.splitlines():
        line = raw.strip()

        if line.startswith("## "):
            if current is not None and current.prose:
                articles.append(current)
            current = Article(line[3:].strip())
            in_when = False
            continue

        if current is None:
            continue

        if line.startswith("**") and not current.name:
            closing = line.find("**", 2)
            if closing > 0:
                current.name = line[2:closing].strip()
                rest = line[closing + 2:].strip()
                current.range = rest.lstrip("—-").strip()
            continue

        if line.startswith("*When to use it:*"):
            current.when = line[len("*When to use it:*"):].strip()
            in_when = True
            continue

        if line.startswith("*Show me:*"):
            in_when = False
            continue

        # A wrapped "When to use it" paragraph continues until a blank line.
        # Taking only its first physical line dropped the rest of the sentence
        # AND appended it to the body, so every one of the 54 rows in the
        # generated table ended mid-clause with an orphan fragment glued to the
        # prose above it.
        if not line:
            in_when = False
            continue

        if in_when:
            current.when += " " + line
            continue

        current.body.append(line)

    if current is not None and current.prose:
        articles.append(current)

    return articles


def family_of(kind: str) -> str:
    for name, prefixes in FAMILY_ORDER:
        for prefix in prefixes:
            if kind.startswith(prefix):
                return name
    return "Other"


def render(articles: list[Article]) -> str:
    out = [
        BEGIN,
        "",
        "<!-- Generated by scripts/gen-docs.py from resources/help/reference.md.",
        "     Edit that file, not this section. -->",
        "",
    ]

    seen: set[str] = set()
    families = [name for name, _ in FAMILY_ORDER] + ["Other"]

    for family in families:
        members = [a for a in articles if family_of(a.kind) == family and a.kind not in seen]

        if not members:
            continue

        out.append(f"### {family}")
        out.append("")
        out.append("| Control | Range | What it does |")
        out.append("|---|---|---|")

        for article in members:
            seen.add(article.kind)
            prose = article.prose.replace("|", "\\|")
            out.append(f"| **{article.name}** | {article.range} | {prose} |")

        out.append("")

    out.append(END)
    return "\n".join(out)


def apply(manual: str, generated: str) -> str:
    if BEGIN in manual and END in manual:
        return re.sub(
            re.escape(BEGIN) + ".*?" + re.escape(END),
            lambda _: generated,
            manual,
            flags=re.S,
        )

    # First run: append a section rather than guessing where it belongs.
    return manual.rstrip() + "\n\n---\n\n## Parameter reference\n\n" + generated + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the manual is out of date, changing nothing")
    args = parser.parse_args()

    if not REFERENCE.is_file():
        print(f"missing {REFERENCE.relative_to(ROOT)}", file=sys.stderr)
        return 1

    articles = parse(REFERENCE.read_text(encoding="utf-8"))

    if not articles:
        print("reference.md produced no articles - has its format changed?", file=sys.stderr)
        return 1

    manual = MANUAL.read_text(encoding="utf-8")
    updated = apply(manual, render(articles))

    if args.check:
        if updated != manual:
            print(
                "docs/MANUAL.md is out of date with resources/help/reference.md.\n"
                "Run scripts/gen-docs.py and commit the result.",
                file=sys.stderr,
            )
            return 1

        print(f"docs/MANUAL.md is up to date ({len(articles)} articles)")
        return 0

    MANUAL.write_text(updated, encoding="utf-8")
    print(f"wrote docs/MANUAL.md from {len(articles)} articles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
